version: '3.8'

services:
    mysql:
        image: mysql:8.0.32
        container_name: stock-management-db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_USER: stockuser
            MYSQL_PASSWORD: stockpassword
            MYSQL_DATABASE: stock_management
        ports:
            - '3306:3306'
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
